<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-12-05T09:40:29Z" name="Nopcommerce" finished-at="2021-12-05T09:40:56Z" duration-ms="26094">
    <groups>
    </groups>
    <test started-at="2021-12-05T09:40:29Z" name="Run on Chrome" finished-at="2021-12-05T09:40:56Z" duration-ms="26094">
      <class name="com.nopcommerce.user.Page_Object_Login">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:com.nopcommerce.user.Page_Object_Login@179ece50]" started-at="2021-12-05T09:40:29Z" name="beforeClass" finished-at="2021-12-05T09:40:38Z" duration-ms="8637" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="Login_01_Empty_Data()[pri:0, instance:com.nopcommerce.user.Page_Object_Login@179ece50]" started-at="2021-12-05T09:40:38Z" name="Login_01_Empty_Data" finished-at="2021-12-05T09:40:40Z" duration-ms="1476" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_01_Empty_Data -->
        <test-method signature="Login_02_Invalid_Email()[pri:0, instance:com.nopcommerce.user.Page_Object_Login@179ece50]" started-at="2021-12-05T09:40:40Z" name="Login_02_Invalid_Email" finished-at="2021-12-05T09:40:41Z" duration-ms="1884" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_02_Invalid_Email -->
        <test-method signature="Login_03_Email_Not_Exist()[pri:0, instance:com.nopcommerce.user.Page_Object_Login@179ece50]" started-at="2021-12-05T09:40:41Z" name="Login_03_Email_Not_Exist" finished-at="2021-12-05T09:40:44Z" duration-ms="2172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_03_Email_Not_Exist -->
        <test-method signature="Login_04_Email_Exist_Null_Password()[pri:0, instance:com.nopcommerce.user.Page_Object_Login@179ece50]" started-at="2021-12-05T09:40:44Z" name="Login_04_Email_Exist_Null_Password" finished-at="2021-12-05T09:40:52Z" duration-ms="8412" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login was unsuccessful. Please correct the errors and try again.
No customer account found] but found [Login was unsuccessful. Please correct the errors and try again.
The credentials provided are incorrect]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login was unsuccessful. Please correct the errors and try again.
No customer account found] but found [Login was unsuccessful. Please correct the errors and try again.
The credentials provided are incorrect]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.nopcommerce.user.Page_Object_Login.Login_04_Email_Exist_Null_Password(Page_Object_Login.java:112)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_04_Email_Exist_Null_Password -->
        <test-method signature="Login_05_Email_Exist_Incorrect_Password()[pri:0, instance:com.nopcommerce.user.Page_Object_Login@179ece50]" started-at="2021-12-05T09:40:52Z" name="Login_05_Email_Exist_Incorrect_Password" finished-at="2021-12-05T09:40:54Z" duration-ms="1567" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login was unsuccessful. Please correct the errors and try again.
No customer account found] but found [Login was unsuccessful. Please correct the errors and try again.
The credentials provided are incorrect]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login was unsuccessful. Please correct the errors and try again.
No customer account found] but found [Login was unsuccessful. Please correct the errors and try again.
The credentials provided are incorrect]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.nopcommerce.user.Page_Object_Login.Login_05_Email_Exist_Incorrect_Password(Page_Object_Login.java:129)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_05_Email_Exist_Incorrect_Password -->
        <test-method signature="Login_06_Correct_Email_Password()[pri:0, instance:com.nopcommerce.user.Page_Object_Login@179ece50]" started-at="2021-12-05T09:40:54Z" name="Login_06_Correct_Email_Password" finished-at="2021-12-05T09:40:56Z" duration-ms="1902" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_06_Correct_Email_Password -->
      </class> <!-- com.nopcommerce.user.Page_Object_Login -->
    </test> <!-- Run on Chrome -->
  </suite> <!-- Nopcommerce -->
</testng-results>
